// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAllowParams creates a new AllowParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAllowParams() *AllowParams {
	return &AllowParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAllowParamsWithTimeout creates a new AllowParams object
// with the ability to set a timeout on a request.
func NewAllowParamsWithTimeout(timeout time.Duration) *AllowParams {
	return &AllowParams{
		timeout: timeout,
	}
}

// NewAllowParamsWithContext creates a new AllowParams object
// with the ability to set a context for a request.
func NewAllowParamsWithContext(ctx context.Context) *AllowParams {
	return &AllowParams{
		Context: ctx,
	}
}

// NewAllowParamsWithHTTPClient creates a new AllowParams object
// with the ability to set a custom HTTPClient for a request.
func NewAllowParamsWithHTTPClient(client *http.Client) *AllowParams {
	return &AllowParams{
		HTTPClient: client,
	}
}

/* AllowParams contains all the parameters to send to the API endpoint
   for the allow operation.

   Typically these are written to a http.Request.
*/
type AllowParams struct {

	// Bid.
	Bid string

	// Exp.
	Exp int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the allow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AllowParams) WithDefaults() *AllowParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the allow params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AllowParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the allow params
func (o *AllowParams) WithTimeout(timeout time.Duration) *AllowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the allow params
func (o *AllowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the allow params
func (o *AllowParams) WithContext(ctx context.Context) *AllowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the allow params
func (o *AllowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the allow params
func (o *AllowParams) WithHTTPClient(client *http.Client) *AllowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the allow params
func (o *AllowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBid adds the bid to the allow params
func (o *AllowParams) WithBid(bid string) *AllowParams {
	o.SetBid(bid)
	return o
}

// SetBid adds the bid to the allow params
func (o *AllowParams) SetBid(bid string) {
	o.Bid = bid
}

// WithExp adds the exp to the allow params
func (o *AllowParams) WithExp(exp int64) *AllowParams {
	o.SetExp(exp)
	return o
}

// SetExp adds the exp to the allow params
func (o *AllowParams) SetExp(exp int64) {
	o.Exp = exp
}

// WriteToRequest writes these params to a swagger request
func (o *AllowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param bid
	qrBid := o.Bid
	qBid := qrBid
	if qBid != "" {

		if err := r.SetQueryParam("bid", qBid); err != nil {
			return err
		}
	}

	// query param exp
	qrExp := o.Exp
	qExp := swag.FormatInt64(qrExp)
	if qExp != "" {

		if err := r.SetQueryParam("exp", qExp); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
