// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BookStatus status of the bookings for an experiment
//
// swagger:model BookStatus
type BookStatus struct {

	// is experiment available
	Available bool `json:"available,omitempty"`

	// why experiment is/isn't available
	Reason string `json:"reason,omitempty"`
}

// Validate validates this book status
func (m *BookStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this book status based on context it is used
func (m *BookStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BookStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BookStatus) UnmarshalBinary(b []byte) error {
	var res BookStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
